E_Insurance/E_Insurance/Models/Compliance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;


namespace E_Insurance.Models
{
    public class Compliance
    {
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        [Key]
        public int Compliance_Id { get; set; }
        [Display(Name="Company Name")]
        public string CompanyName  { get; set; }
        [Display(Name="Registration No.")]
        public string RegistrationNo { get; set; }
        public int Employer_Id { get; set; }

        public bool Approve { get; set; }
        

        public virtual Employer Employer { get; set; }
    }
}

E_Insurance/E_Insurance/Controllers/ComplianceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Insurance.Models;

namespace E_Insurance.Controllers
{
    public class ComplianceController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly HttpContext _context = System.Web.HttpContext.Current;

        // GET: /Compliance/
        //[Authorize(Roles="Admin")]
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var emp = db.Compliances.Include(c => c.Employer);
            return View(emp.ToList());
        }

        // GET: /Compliance/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compliance compliance = db.Compliances.Find(id);
            if (compliance == null)
            {
                return HttpNotFound();
            }
            return View(compliance);
        }

        // GET: /Compliance/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Compliance/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Compliance_Id,CompanyName,RegistrationNo,Employer_Id")] Compliance compliance)
        {
            if (ModelState.IsValid)
            {
                if(_context.Session["Employer_Id"] == null)
                {
                    return RedirectToAction("EmployerLogin", "Employer");
                }
                int id = (int)_context.Session["Employer_Id"];
                compliance.Employer_Id = id;
                db.Compliances.Add(compliance);
                db.SaveChanges();
                return RedirectToAction("ComplianceSuccess");
            }

            return View(compliance);
        }


        public ViewResult ComplianceSuccess()
        {
            @ViewBag.ComplianceMsg = "Your Request was Successful";

            return View();

        }
        public ActionResult ComplianceApproval(int? id)
        {
            ComplianceActivity compActivity = new ComplianceActivity();
            Compliance comp = db.Compliances.Find(id);
            if (comp.Approve != true)
            {
                comp.Approve = true;
                db.SaveChanges();
            }
            return View();
        }
        //[Authorize(Roles = "Admin")]
        [Authorize(Roles = "Admin")]
        public ViewResult ApproveCompliance(int id)
        {

            Compliance claim = db.Compliances.Find(id);


            return View(claim);
        }

        public ViewResult ViewApproval(int id)
        {

            Compliance comp = db.Compliances.Find(id);


            return View(comp);
        }


        public ActionResult PrintReceipt(int? id)
        {
            if (_context.Session["Employer_Id"] == null)
            {
                return RedirectToAction("EmployerLogin", "Employer");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var claims = db.Compliances.Find(id);
            if (claims == null)
            {
                return HttpNotFound();
            }
            return View(claims);
        }
        public ActionResult ViewApprovals()
        {
            int id = (int)(_context.Session["Employer_Id"]);
            var claims = db.Compliances.Include(emp => emp.Employer).Where(emp => emp.Employer_Id == id).ToList();

            return View(claims);
        }
        // GET: /Compliance/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compliance compliance = db.Compliances.Find(id);
            if (compliance == null)
            {
                return HttpNotFound();
            }
            return View(compliance);
        }

        // POST: /Compliance/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Compliance_Id,CompanyName,RegistrationNo,EmployerId")] Compliance compliance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compliance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(compliance);
        }

        // GET: /Compliance/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compliance compliance = db.Compliances.Find(id);
            if (compliance == null)
            {
                return HttpNotFound();
            }
            return View(compliance);
        }

        // POST: /Compliance/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compliance compliance = db.Compliances.Find(id);
            db.Compliances.Remove(compliance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_Insurance/E_Insurance/Views/Compliance/ApproveCompliance.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "ApproveCompliance";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div>
    <h2>Approve Compliance</h2>

	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Employer_Name)
        </dd>

       
      

    </dl>
</div>
<p>
    @Html.ActionLink("Approve", "ComplianceApproval", new { id = Model.Compliance_Id })
</p>

<p style="text-align:center">
    @if(Model.Approve == true)
    {
        <h2>
            Approved
        </h2>
    }
    else
    {
        <h2>

            Not Approved
        </h2>
    }
</p>

E_Insurance/E_Insurance/Views/Compliance/ComplianceApproval.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "ComplianceApproval";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2 style="text-align:center">Approval Successful</h2>

E_Insurance/E_Insurance/Views/Compliance/ComplianceSuccess.cshtml
@{
    ViewBag.Title = "ComplianceSuccess";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">
    @ViewBag.ComplianceMsg
    
</h2>

E_Insurance/E_Insurance/Views/Compliance/Create.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

@using (Html.BeginForm("Create","Compliance",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2 style=" text-align:center">Request for Compliance Certificate</h2>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNo)
                @Html.ValidationMessageFor(model => model.RegistrationNo)
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

E_Insurance/E_Insurance/Views/Compliance/Delete.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compliance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployerId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E_Insurance/E_Insurance/Views/Compliance/Details.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Compliance</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployerId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Compliance_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

E_Insurance/E_Insurance/Views/Compliance/Edit.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compliance</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Compliance_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNo)
                @Html.ValidationMessageFor(model => model.RegistrationNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployerId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployerId)
                @Html.ValidationMessageFor(model => model.EmployerId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E_Insurance/E_Insurance/Views/Compliance/Index.cshtml
@model IEnumerable<E_Insurance.Models.Compliance>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>List of Compliance Certificate Request</h2>


<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employer.Employer_Name)
        </td>
        <td>
            
            @Html.ActionLink("Approve Compliance", "ApproveCompliance", new { id = item.Compliance_Id })
        </td>
    </tr>
}

</table>

E_Insurance/E_Insurance/Views/Compliance/PrintReceipt.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "PrintReceipt";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}
@{

    var emp_Name = Model.Employer.Employer_Name;
    var regNo = Model.Employer.Registration_No;
    var word = "We Dearly Approve Your Compliance by presenting You with this Cerificate";
    var myTitle = "Compliance Certificate";
}
<input type="hidden" id="txtTitle" name="txtTitle" value="@myTitle" />
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">@myTitle</h3>
    </div>


    <div class="panel-body" id="dataexample3">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label" style="font-weight: 300; font-family:'Franklin Gothic'">EMPLOYER NAME.:</label>
                    &nbsp;<label class="control-label">@emp_Name</label>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label" style="font-weight: 300; font-family: 'Franklin Gothic'">EMPLOYER REG NO.:</label>
                    &nbsp;<label class="control-label">@regNo</label>
                </div>
            </div>


            <div class="col-md-6">
                <div class="form-group jumbotron">
                    <label class="control-label" style="font-weight: 400; text-align:center; font-family:'Franklin Gothic'">Word of Compliance</label>
                    &nbsp;<label class="control-label">@word</label>
                </div>
            </div>
           </div>
    </div>
</div>
<a id="printResult" class="btn btn-info">
    <span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print
</a>
@section Scripts {

    <script src="~/Scripts/jquery-printme.js"></script>

    <script type="text/javascript">

        $("#printResult").click(function () {
            var title = $("#txtTitle").val();
            $("#dataexample3").printMe({
                "path": ["../../Content/print.css"],
                "title": title
            });
            return (false);
        });

    </script>
}

E_Insurance/E_Insurance/Views/Compliance/ViewApproval.cshtml
@model E_Insurance.Models.Compliance

@{
    ViewBag.Title = "ViewApproval";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}
@if(!Model.Approve == true)
{
    <h2>
        Not Yet Approved Check Back Later
</h2>        
}
else
{ 
<h2>View Approval</h2>

<div>
    <h4>Compliance</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Employer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

       
    </dl>

    <p>
        <a href="/Compliance/PrintReceipt/@Model.Compliance_Id" class="btn btn-info">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> View Certificate
        </a>
    </p>
</div>
}

E_Insurance/E_Insurance/Views/Compliance/ViewApprovals.cshtml
@model IEnumerable<E_Insurance.Models.Compliance>

@{
    ViewBag.Title = "ViewApprovals";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2>View Approvals</h2>


<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employer.Employer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationNo)
        </td>
        
        <td>
            
            @Html.ActionLink("View Approval", "ViewApproval", new { id=item.Compliance_Id })
        </td>
    </tr>
}

</table>