E_Insurance/E_Insurance/Models/Case.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace E_Insurance.Models
{
    public class Case
    {
        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        //Case
        public  int Id { get; set; }
        [Display(Name="Case Number")]
        public string Case_No { get; set; }
        
        
        //Employee
        
        public string Employee_Surname { get; set; }
        [Display(Name = "First Name")]
        public string Employee_FirstName { get; set; }
        [Display(Name = "Middle Name")]
        public string Employee_MiddleName { get; set; }
        [Display(Name = "Salary")]
        public double Salary { get; set; }
        [Display(Name = "Date of Incident")]
        public DateTime Incident_Date { get; set; }
        [Display(Name = "Time of Incident")]
        public string Time_of_Incident { get; set; }
        [Display(Name = "Town  of Incident")]
        public string Town { get; set; }
        [Display(Name = "LGA of Incident")]
        public string LGA { get; set; }
        [Display(Name = "State of Incident")]
        public string State { get; set; }
        [Display(Name = "Date of Report")]
        public DateTime Incident_Report_Date { get; set; }
        [Display(Name = "Type of Incident")]
        public string TypeOfIncident { get; set; }
        [Display(Name = "Employer")]
        public int Employer_Id { get; set; }


        public virtual Employer Employer { get; set; }
        
    }
}

E_Insurance/E_Insurance/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Insurance.Models;

namespace E_Insurance.Controllers
{
    public class CaseController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private readonly HttpContext _context = System.Web.HttpContext.Current;

        // GET: /Case/
        public ActionResult Index()
        {
            var cases = db.Cases.Include(a => a.Employer);
            return View(cases.ToList());
        }


        public ActionResult ViewCases(int? id)
        {
            if (_context.Session["employee_Id"] == null)
            {
                return RedirectToAction("EmployerLogin", "Employer");
            }
            var empl = db.Employers.Find(id);
            var employer = db.Cases.Where(emp => emp.Employer_Id == id);

            return View(employer.ToList());
        }
        // GET: /Case/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            return View(@case);
        }

        // GET: /Case/Create
        public ActionResult Create()
        {
            if (_context.Session["Employer_Id"] == null)
            {
                return RedirectToAction("EmployerLogin", "Employer");
            }
            ViewBag.Employer_Id = new SelectList(db.Employers, "Employer_Id", "Employer_Name");
            return View();
        }

        // POST: /Case/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Case_No,Employee_Surname,Employee_FirstName,Employee_MiddleName,Salary,Incident_Date,Time_of_Incident,Town,LGA,State,Incident_Report_Date,TypeOfIncident,Employer_Id")] Case @case)
        {
            if (ModelState.IsValid)
            {


                @case.Case_No = GenerateCaseNo(@case.Id);

                db.Cases.Add(@case);
                db.SaveChanges();
                return RedirectToAction("Dashboard", "Employer");
            }

            ViewBag.Employer_Id = new SelectList(db.Employers, "Employer_Id", "Employer_Name", @case.Employer_Id);
            return View(@case);
        }



        public string GenerateCaseNo(int id)
        {
            var emp = db.Cases.FirstOrDefault(m => m.Id == id);
            var rand = new Random();
            var Nrand = rand.Next(50000000, 80000000);
            return emp + Nrand.ToString();

        }




        // GET: /Case/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            ViewBag.Employer_Id = new SelectList(db.Employers, "Employer_Id", "Employer_Name", @case.Employer_Id);
            return View(@case);
        }

        // POST: /Case/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Case_No,Employee_Surname,Employee_FirstName,Employee_MiddleName,Salary,Incident_Date,Time_of_Incident,Town,LGA,State,Incident_Report_Date,TypeOfIncident,Employer_Id")] Case @case)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@case).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Employer_Id = new SelectList(db.Employers, "Employer_Id", "Employer_Name", @case.Employer_Id);
            return View(@case);
        }

        // GET: /Case/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            return View(@case);
        }

        // POST: /Case/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Case @case = db.Cases.Find(id);
            db.Cases.Remove(@case);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_Insurance/E_Insurance/Views/Case/Create.cshtml
@model E_Insurance.Models.Case

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}



@using (Html.BeginForm("Create","Case",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Report Employee Case</h4>
        <hr />
        @Html.ValidationSummary(true)

        
        <div class="form-group">
            @Html.LabelFor(model => model.Employee_Surname,"Surname", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Employee_Surname , new{@class="form-control", @placeholder="Enter Employee's Surname"})
                @Html.ValidationMessageFor(model => model.Employee_Surname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Employee_FirstName, new { @class = "form-control", @placeholder = "Enter Employee's First Name" })
                @Html.ValidationMessageFor(model => model.Employee_FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_MiddleName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Employee_MiddleName, new { @class = "form-control", @placeholder = "Enter Employee's Middle Name" })
                @Html.ValidationMessageFor(model => model.Employee_MiddleName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Salary, new { @class = "form-control", @placeholder = "Enter Employee's Salary" })
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Incident_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Incident_Date, new { @class = "form-control", @placeholder = "Enter Incident Date" })
                @Html.ValidationMessageFor(model => model.Incident_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_of_Incident, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Time_of_Incident, new { @class = "form-control", @placeholder = "Enter Time of Incident" })
                @Html.ValidationMessageFor(model => model.Time_of_Incident)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Town, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Town, new { @class = "form-control", @placeholder = "Enter Town of Incident" })
                @Html.ValidationMessageFor(model => model.Town)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LGA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LGA, new { @class = "form-control", @placeholder = "Enter Local Government of Incident" })
                @Html.ValidationMessageFor(model => model.LGA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.State, new { @class = "form-control", @placeholder = "Enter State of Incident" })
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Incident_Report_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Incident_Report_Date, new { @class = "form-control", @placeholder = "Enter Date Reported" })
                @Html.ValidationMessageFor(model => model.Incident_Report_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfIncident, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeOfIncident, new List<SelectListItem>
                {
                    new SelectListItem{ Text="Accident", Value="Accident"},
                    new SelectListItem{ Text="Death", Value="Death"},
                    new SelectListItem{Text="Occupational Disease", Value="Occupational Disease"}

                }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfIncident)
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Notification" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>

$(document).ready(function () {
              $("#datepicker").datepicker({ format: 'yyyy-mm-dd', value: '2016-05-7' });
           // $('.datepicker').datepicker();
            // $("#messageDiv").text("");

            $("#success-alert").fadeTo(2000, 500).slideUp(500, function () {
                $("#success-alert").alert('close');
            });
        });



    </script>

E_Insurance/E_Insurance/Views/Case/Delete.cshtml
@model E_Insurance.Models.Case

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Case</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Employer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Case_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Incident_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_of_Incident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_of_Incident)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LGA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LGA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Incident_Report_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Report_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfIncident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfIncident)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E_Insurance/E_Insurance/Views/Case/Details.cshtml
@model E_Insurance.Models.Case

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Case</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Employer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Case_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Incident_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_of_Incident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_of_Incident)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LGA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LGA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Incident_Report_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Report_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfIncident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfIncident)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

E_Insurance/E_Insurance/Views/Case/Edit.cshtml
@model E_Insurance.Models.Case

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Case</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Case_No, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Case_No)
                @Html.ValidationMessageFor(model => model.Case_No)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_Surname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Employee_Surname)
                @Html.ValidationMessageFor(model => model.Employee_Surname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Employee_FirstName)
                @Html.ValidationMessageFor(model => model.Employee_FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_MiddleName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Employee_MiddleName)
                @Html.ValidationMessageFor(model => model.Employee_MiddleName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary)
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Incident_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Incident_Date)
                @Html.ValidationMessageFor(model => model.Incident_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_of_Incident, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_of_Incident)
                @Html.ValidationMessageFor(model => model.Time_of_Incident)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Town, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Town)
                @Html.ValidationMessageFor(model => model.Town)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LGA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LGA)
                @Html.ValidationMessageFor(model => model.LGA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Incident_Report_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Incident_Report_Date)
                @Html.ValidationMessageFor(model => model.Incident_Report_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfIncident, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeOfIncident)
                @Html.ValidationMessageFor(model => model.TypeOfIncident)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employer_Id, "Employer_Id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Employer_Id", String.Empty)
                @Html.ValidationMessageFor(model => model.Employer_Id)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E_Insurance/E_Insurance/Views/Case/Index.cshtml
@model IEnumerable<E_Insurance.Models.Case>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>


<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Employer.Employer_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Case_No)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_MiddleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Incident_Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time_of_Incident)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Town)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LGA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Incident_Report_Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfIncident)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employer.Employer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Case_No)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_MiddleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Incident_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time_of_Incident)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Town)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LGA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Incident_Report_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfIncident)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

E_Insurance/E_Insurance/Views/Case/ViewCases.cshtml
@model IEnumerable<E_Insurance.Models.Case>

@{
    ViewBag.Title = "ViewCases";
    Layout = "~/Views/Shared/_LayoutEmployer.cshtml";
}

<h2 style="text-align:center">List Of Cases</h2>


<table class="table table-striped table-bordered" >
    <tr>
        <th>
            Employer Name
        </th>
        <th>
            Case No.
        </th>
        <th>
            Surname
        </th>
        <th>
            First Name
        </th>
        <th>
           Middle Name
        </th>
        <th>
            Salary
        </th>
        <th>
            Incident Date
        </th>
        <th>
            Incident Time
        </th>
        <th>
            Incident Town
        </th>
        <th>
            LGA
        </th>
        <th>
            State
        </th>
        <th>
            Report Date
        </th>
        <th>
           Incident Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employer.Employer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Case_No)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee_MiddleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Incident_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time_of_Incident)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Town)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LGA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Incident_Report_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfIncident)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>*@
    </tr>
}

</table>